### ISSUE TITLE
Asking for Advice

### ISSUE THREAD

**Issue by kuator** [aca/dotfiles#1]
Hi, I really loved your pylance.nvim plugin. I don't know how you were able to find the workarounds, but they worked beautifully. The problem is "they worked", now they don't unfortunately. So, I would like to ask maybe you know a new workaround around the license. I really love neovim and I really don't like Visual Studio Code

**Comment by aca** [comment]
@kuator I had to remove the repository because of license issues. I've received some warnings from Microsoft. It would work until 2021.02. You should force the version inside the install script, If you still have the repo. 

Since 2021.03, They have slightly changed their tricks. But you can still 'hack' the server as it is just javascript.
Beautify the code, and search for readable string. Wouldn't be that hard. That's all I can tell.

**Comment by kuator** [comment]
Thanks! I will switch to jedi or pyls if needed, only not to use Visual Studio Code.
